"""create movies table

Revision ID: b2f96df5e466
Revises: 
Create Date: 2025-04-18 19:04:13.264157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f96df5e466'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kp_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('alternativeName', sa.String(), nullable=True),
    sa.Column('enName', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('typeNumber', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('shortDescription', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('rating', sa.JSON(), nullable=True),
    sa.Column('votes', sa.JSON(), nullable=True),
    sa.Column('movieLength', sa.Integer(), nullable=True),
    sa.Column('ageRating', sa.Integer(), nullable=True),
    sa.Column('poster', sa.JSON(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('countries', sa.JSON(), nullable=True),
    sa.Column('persons', sa.JSON(), nullable=True),
    sa.Column('budget', sa.JSON(), nullable=True),
    sa.Column('fees', sa.JSON(), nullable=True),
    sa.Column('premier', sa.JSON(), nullable=True),
    sa.Column('seq_and_preq', sa.JSON(), nullable=True),
    sa.Column('watchability', sa.JSON(), nullable=True),
    sa.Column('top10', sa.Integer(), nullable=True),
    sa.Column('top250', sa.Integer(), nullable=True),
    sa.Column('tickets_on_sale', sa.Boolean(), nullable=True),
    sa.Column('lists', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
