"""create movies table

Revision ID: e5a92dc98108
Revises: 
Create Date: 2025-04-21 19:51:39.315774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5a92dc98108'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('alt_name', sa.String(), nullable=True),
    sa.Column('en_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('type_number', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('rating', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('votes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('movie_length', sa.Integer(), nullable=True),
    sa.Column('age_rating', sa.Integer(), nullable=True),
    sa.Column('poster', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('countries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('persons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('premier', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seq_and_preq', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('watchability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top10', sa.Integer(), nullable=True),
    sa.Column('top250', sa.Integer(), nullable=True),
    sa.Column('tickets_on_sale', sa.Boolean(), nullable=True),
    sa.Column('lists', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
