"""create videocdn movies table

Revision ID: ef9721d811a0
Revises: e5a92dc98108
Create Date: 2025-04-29 10:32:27.174754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef9721d811a0'
down_revision: Union[str, None] = 'e5a92dc98108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videocdn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('videocdn_id', sa.String(), nullable=True),
    sa.Column('ru_title', sa.String(), nullable=True),
    sa.Column('orig_title', sa.String(), nullable=True),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('kinopoisk_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.String(), nullable=True),
    sa.Column('released', sa.String(), nullable=True),
    sa.Column('updated', sa.String(), nullable=True),
    sa.Column('iframe_src', sa.String(), nullable=True),
    sa.Column('iframe', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_media_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videocdn')
    # ### end Alembic commands ###
